package com.privateflow.modules.customer.infra;

import com.privateflow.modules.customer.Customer;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;

public class CustomerRowMapper implements RowMapper<Customer> {

  @Override
  public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
    Customer customer = new Customer();
    customer.setId(rs.getLong("id"));
    customer.setPhone(rs.getString("phone"));
    customer.setNickname(rs.getString("nickname"));
    customer.setCustomerName(rs.getString("customer_name"));
    customer.setWechatId(rs.getString("wechat_id"));
    customer.setSourceChannel(rs.getString("source_channel"));
    customer.setLeadType(rs.getString("lead_type"));
    customer.setLeadCaptureType(rs.getString("lead_capture_type"));
    customer.setLeadCaptureMethod(rs.getString("lead_capture_method"));
    customer.setPlatformLeadAt(rs.getTimestamp("platform_lead_at") == null ? null : rs.getTimestamp("platform_lead_at").toLocalDateTime());
    customer.setAdvertisingType(rs.getString("advertising_type"));
    customer.setGlobalAdvertisementId(rs.getString("global_advertisement_id"));
    customer.setStandardAdvertisementId(rs.getString("standard_advertisement_id"));
    customer.setContentId(rs.getString("content_id"));
    customer.setVideoId(rs.getString("video_id"));
    customer.setOrderNumber(rs.getString("order_number"));
    customer.setConversionTrace(rs.getString("conversion_trace"));
    customer.setPersonalityType(rs.getString("personality_type"));
    customer.setAssignedKeeper(rs.getString("assigned_keeper"));
    customer.setAssignedAt(rs.getTimestamp("assigned_at") == null ? null : rs.getTimestamp("assigned_at").toLocalDateTime());
    customer.setLeadInitialProcessedAt(rs.getTimestamp("lead_initial_processed_at") == null ? null : rs.getTimestamp("lead_initial_processed_at").toLocalDateTime());
    customer.setLeadInitialProcessedBy(rs.getString("lead_initial_processed_by"));
    customer.setLeadRetainedUntil(rs.getTimestamp("lead_retained_until") == null ? null : rs.getTimestamp("lead_retained_until").toLocalDateTime());
    customer.setLeadInvalid(rs.getBoolean("lead_invalid"));
    customer.setPreviousAssignedKeeper(rs.getString("previous_assigned_keeper"));
    customer.setPreviousPlatformLeadAt(rs.getTimestamp("previous_platform_lead_at") == null ? null : rs.getTimestamp("previous_platform_lead_at").toLocalDateTime());
    customer.setAssignmentMonth(rs.getString("assignment_month"));
    customer.setIntendedStore(rs.getString("intended_store"));
    customer.setIntendedProject(rs.getString("intended_project"));
    customer.setPurchasedProject(rs.getString("purchased_project"));
    customer.setExperienceCardType(rs.getString("experience_card_type"));
    customer.setPendingOrderStatus(rs.getString("pending_order_status"));
    customer.setPurchaseDate(rs.getDate("purchase_date") == null ? null : rs.getDate("purchase_date").toLocalDate());
    customer.setCustomerLevel(rs.getString("customer_level"));
    customer.setPostpartumMonths(rs.getBigDecimal("postpartum_months"));
    customer.setParity(rs.getString("parity"));
    customer.setDeliveryMethod(rs.getString("delivery_method"));
    customer.setBreastfeeding(rs.getString("breastfeeding"));
    customer.setLochiaPeriod(rs.getString("lochia_period"));
    customer.setPregnancyWeight(rs.getBigDecimal("pregnancy_weight"));
    customer.setCurrentWeight(rs.getBigDecimal("current_weight"));
    customer.setBodyConcerns(rs.getString("body_concerns"));
    customer.setDiastasisRecti(rs.getString("diastasis_recti"));
    customer.setUrineLeakage(rs.getString("urine_leakage"));
    customer.setPubicLumbago(rs.getString("pubic_lumbago"));
    customer.setPrevRepairExp(rs.getString("prev_repair_exp"));
    customer.setPostpartumCheck(rs.getString("postpartum_check"));
    customer.setExerciseHabits(rs.getString("exercise_habits"));
    customer.setIntentLevel(rs.getString("intent_level"));
    customer.setWorries(rs.getString("worries"));
    customer.setCustomerStage(rs.getString("customer_stage"));
    customer.setInternalNote(rs.getString("internal_note"));
    customer.setCustomerProfileSummary(rs.getString("customer_profile_summary"));
    customer.setFirstTrackingCapture(rs.getString("first_tracking_capture"));
    customer.setSecondTrackingCapture(rs.getString("second_tracking_capture"));
    customer.setThirdTrackingCapture(rs.getString("third_tracking_capture"));
    customer.setLastFollowupAt(rs.getTimestamp("last_followup_at") == null ? null : rs.getTimestamp("last_followup_at").toLocalDateTime());
    customer.setFollowupNotes(rs.getString("followup_notes"));
    customer.setNextFollowupAt(rs.getTimestamp("next_followup_at") == null ? null : rs.getTimestamp("next_followup_at").toLocalDateTime());
    customer.setNextFollowupDir(rs.getString("next_followup_dir"));
    customer.setAppointmentDate(rs.getDate("appointment_date") == null ? null : rs.getDate("appointment_date").toLocalDate());
    customer.setAppointmentStore(rs.getString("appointment_store"));
    customer.setAppointmentItem(rs.getString("appointment_item"));
    customer.setArrived(rs.getString("arrived"));
    customer.setAppointmentStatus(rs.getString("appointment_status"));
    customer.setAppointmentTime(rs.getString("appointment_time"));
    customer.setArrivalSourceRowId(rs.getString("arrival_source_row_id"));
    customer.setArrivalHandoverRecord(rs.getString("arrival_handover_record"));
    customer.setArrivalProjectType(rs.getString("arrival_project_type"));
    customer.setArrivalExperienceProject(rs.getString("arrival_experience_project"));
    customer.setHistoricalExperienceCount(rs.getString("historical_experience_count"));
    customer.setCustomerReport(rs.getString("customer_report"));
    customer.setReceptionTeacher(rs.getString("reception_teacher"));
    customer.setReceptionConsultant(rs.getString("reception_consultant"));
    customer.setVoucherRedeemed(rs.getString("voucher_redeemed"));
    customer.setTransactionAmount(rs.getBigDecimal("transaction_amount"));
    customer.setTransactionAt(rs.getTimestamp("transaction_at") == null ? null : rs.getTimestamp("transaction_at").toLocalDateTime());
    customer.setTransactionPrimaryReason(rs.getString("transaction_primary_reason"));
    customer.setSourceTable(rs.getString("source_table"));
    customer.setSourceRowId(rs.getString("source_row_id"));
    customer.setSyncedAt(rs.getTimestamp("synced_at") == null ? null : rs.getTimestamp("synced_at").toLocalDateTime());
    customer.setVersion(rs.getInt("version"));
    customer.setCreatedAt(rs.getTimestamp("created_at") == null ? null : rs.getTimestamp("created_at").toLocalDateTime());
    customer.setUpdatedAt(rs.getTimestamp("updated_at") == null ? null : rs.getTimestamp("updated_at").toLocalDateTime());
    return customer;
  }
}
