package com.privateflow.modules.supervision;

public enum SupervisionEventType {
  TASK_CREATED,
  RECOGNITION_PROCESSED,
  RECOGNITION_SUCCEEDED,
  RECOGNITION_FAILED,
  REPLY_GENERATED,
  REPLY_COPIED,
  REPLY_REGENERATED,
  HELP_REQUESTED,
  TEMPLATE_SAVED,
  TEMPLATE_COPIED
}
