package com.privateflow.modules.supervision;

public enum SupervisionEventType {
  TASK_CREATED,
  PENDING_ENTERED,
  RECOGNITION_SUCCEEDED,
  RECOGNITION_FAILED,
  CUSTOMER_SELECTED,
  REPLY_GENERATED,
  REPLY_COPIED,
  REPLY_REGENERATED,
  HELP_REQUESTED,
  TEMPLATE_SAVED,
  TEMPLATE_COPIED
}
