CREATE TABLE IF NOT EXISTS arrival_handover_tasks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  phone VARCHAR(50) NOT NULL,
  assigned_keeper VARCHAR(100) DEFAULT NULL,
  appointment_date DATE NOT NULL,
  appointment_time VARCHAR(30) DEFAULT NULL,
  appointment_store VARCHAR(100) NOT NULL,
  appointment_item VARCHAR(200) DEFAULT NULL,
  visit_type VARCHAR(100) DEFAULT NULL,
  voucher_redeemed VARCHAR(100) DEFAULT NULL,
  experience_project VARCHAR(500) DEFAULT NULL,
  project_type VARCHAR(100) DEFAULT NULL,
  historical_experience_count VARCHAR(100) DEFAULT NULL,
  customer_report TEXT DEFAULT NULL,
  task_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  sync_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  wecom_row_id VARCHAR(100) DEFAULT NULL,
  sync_retry_count INT NOT NULL DEFAULT 0,
  next_sync_at DATETIME DEFAULT NULL,
  sync_error VARCHAR(500) DEFAULT NULL,
  reminded_at DATETIME DEFAULT NULL,
  completed_by VARCHAR(100) DEFAULT NULL,
  completed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_arrival_handover_pending (task_status, assigned_keeper, updated_at),
  INDEX idx_arrival_handover_sync (sync_status, next_sync_at),
  INDEX idx_arrival_handover_booking (phone, appointment_date, appointment_time, appointment_store, appointment_item)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='预约到店人工补充事项及企业微信到店表写入状态';
